// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsASAQ_GhagCWMGACAlG90I17UfIrkHWA',
    appId: '1:517894244054:web:d918e464dbfcf028deab77',
    messagingSenderId: '517894244054',
    projectId: 'management-c7d7e',
    authDomain: 'management-c7d7e.firebaseapp.com',
    storageBucket: 'management-c7d7e.firebasestorage.app',
    measurementId: 'G-J485FGYBPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOzZiQkuas1n31t7qBemV816vXdcn_mxk',
    appId: '1:517894244054:android:beab14f072ee6c77deab77',
    messagingSenderId: '517894244054',
    projectId: 'management-c7d7e',
    storageBucket: 'management-c7d7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MIiGU-Gu4uy9zOgfcmlePIjxIuMXI30',
    appId: '1:517894244054:ios:09d80b20ed60b31ddeab77',
    messagingSenderId: '517894244054',
    projectId: 'management-c7d7e',
    storageBucket: 'management-c7d7e.firebasestorage.app',
    iosClientId: '517894244054-eth1indq70al532aq0iupsk7vklv84co.apps.googleusercontent.com',
    iosBundleId: 'com.example.management',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MIiGU-Gu4uy9zOgfcmlePIjxIuMXI30',
    appId: '1:517894244054:ios:09d80b20ed60b31ddeab77',
    messagingSenderId: '517894244054',
    projectId: 'management-c7d7e',
    storageBucket: 'management-c7d7e.firebasestorage.app',
    iosClientId: '517894244054-eth1indq70al532aq0iupsk7vklv84co.apps.googleusercontent.com',
    iosBundleId: 'com.example.management',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsASAQ_GhagCWMGACAlG90I17UfIrkHWA',
    appId: '1:517894244054:web:18d41a5219bfbc15deab77',
    messagingSenderId: '517894244054',
    projectId: 'management-c7d7e',
    authDomain: 'management-c7d7e.firebaseapp.com',
    storageBucket: 'management-c7d7e.firebasestorage.app',
    measurementId: 'G-PRZ7GK1FT3',
  );
}
